W8/W8D1/reddit_clone/reddit_clone/config/routes.rb
Rails.application.routes.draw do
    resources :comments, except: [:new, :show]
    resources :posts do    # , except: %i[index]
        resources :comments, only: [:new, :show]
    end
    resources :subs do
    end
    resource :session, only: %i[new create destroy]
    resources :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W8/W8D1/reddit_clone/reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, presence: true
    validates :title, uniqueness: true

    belongs_to :moderator, class_name: :User
    has_many :post_subs, dependent: :destroy, inverse_of: :sub
end

W8/W8D1/reddit_clone/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :set_sub, only: %i[show edit update destroy require_moderator]
    before_action :require_moderator, only: %i[update edit]
    before_action :require_login

    # GET /subs
    # GET /subs.json
    def index
        @subs = Sub.all
    end

    # GET /subs/1
    # GET /subs/1.json
    def show; end

    # GET /subs/new
    def new
        @sub = Sub.new
    end

    # GET /subs/1/edit
    def edit; end

    # POST /subs
    # POST /subs.json
    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        respond_to do |format|
            if @sub.save
                format.html { redirect_to @sub, notice: 'Sub was successfully created.' }
                format.json { render :show, status: :created, location: @sub }
            else
                format.html { render :new }
                format.json { render json: @sub.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /subs/1
    # PATCH/PUT /subs/1.json
    def update
        respond_to do |format|
            if @sub.update(sub_params)
                format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
                format.json { render :show, status: :ok, location: @sub }
            else
                format.html { render :edit }
                format.json { render json: @sub.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /subs/1
    # DELETE /subs/1.json
    def destroy
        @sub.destroy
        respond_to do |format|
            format.html { redirect_to subs_url, notice: 'Sub was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_sub
        @sub = Sub.find(params[:id])
    end

    def require_moderator
        if current_user.id != @sub.moderator_id
            flash[:errors] = ['U need to be a moderator']
            redirect_to @sub
        end
    end

    # Only allow a list of trusted parameters through.
    def sub_params
        params.require(:sub).permit(:title, :description, :moderator_id)
    end
end

W8/W8D1/reddit_clone/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

W8/W8D1/reddit_clone/reddit_clone/app/views/subs/_form.html.erb
<%= form_with(model: sub, local: true) do |form| %>
  <% if sub.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(sub.errors.count, "error") %> prohibited this sub from being saved:</h2>
      <ul>
      <% sub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

W8/W8D1/reddit_clone/reddit_clone/app/views/subs/edit.html.erb
<h1>Editing Sub</h1>

<%= render 'form', sub: @sub %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

W8/W8D1/reddit_clone/reddit_clone/app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Moderator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= sub.title %></td>
        <td><%= sub.description %></td>
        <td><%= sub.moderator.username %></td>
        <td><%= link_to "Show", sub %></td>
        <td><%= link_to "Edit", edit_sub_path(sub) %></td>
        <td><%= link_to "Destroy", sub, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Sub", new_sub_path %>

W8/W8D1/reddit_clone/reddit_clone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render 'form', sub: @sub %>

<%= link_to 'Back', subs_path %>

W8/W8D1/reddit_clone/reddit_clone/app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>
  <% if flash[:errors] %>

    <div id="error_explanation">
      <h2><%= pluralize(flash[:errors].count, "error") %> prohibited this sub from being saved:</h2>
      <ul>
      <% flash[:errors].each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <strong>Title:</strong>
  <%= @sub.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sub.description %>
</p>

<p>
  <strong>Moderator:</strong>
  <%= @sub.moderator.username %>
</p>

<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>