W8/W8D1/reddit_clone/reddit_clone/config/routes.rb
Rails.application.routes.draw do
    resources :comments, except: [:new, :show]
    resources :posts do    # , except: %i[index]
        resources :comments, only: [:new, :show]
    end
    resources :subs do
    end
    resource :session, only: %i[new create destroy]
    resources :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W8/W8D1/reddit_clone/reddit_clone/app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, :post_id, :author_id, presence: true

    belongs_to :author, class_name: :User
    belongs_to :post
    belongs_to :comment, foreign_key: :parent_comment_id, optional: true
    has_many :child_comments, foreign_key: :parent_comment_id, class_name: :Comment
end

W8/W8D1/reddit_clone/reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: %i[show edit update destroy]

    # GET /comments
    # GET /comments.json
    def index
        @comments = Comment.all
    end

    def new
        @comment = Comment.new
    end

    # GET /comments/1
    # GET /comments/1.json
    def show; end

    # GET /comments/1/edit
    def edit; end

    # POST /comments
    # POST /comments.json
    def create
        @comment = Comment.new(comment_params)
        @comment.author_id = current_user.id
        respond_to do |format|
            if @comment.save
                format.html { redirect_to post_url(@comment.post), notice: 'Comment was successfully created.' }
                format.json { render :show, status: :created, location: @comment }
            else
                format.html { render post_url(@comment.post) }
                format.json { render json: @comment.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /comments/1
    # PATCH/PUT /comments/1.json
    def update
        respond_to do |format|
            if @comment.update(comment_params)
                format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
                format.json { render :show, status: :ok, location: @comment }
            else
                format.html { render :edit }
                format.json { render json: @comment.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /comments/1
    # DELETE /comments/1.json
    def destroy
        @comment.destroy
        respond_to do |format|
            format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
        @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
        params.require(:comment).permit(:content, :author_id, :post_id, :parent_comment_id)
    end
end

W8/W8D1/reddit_clone/reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

W8/W8D1/reddit_clone/reddit_clone/app/views/comments/_comment.html.erb
<ul>
    <li><%= link_to comment.content, post_comment_url(comment.post, comment) %></li>
    <% comment.child_comments.each do |child| %>
        <%= render "comment", comment: child %> 
   <% end %> 
</ul>

W8/W8D1/reddit_clone/reddit_clone/app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


    <%= form.hidden_field :post_id, value: params[:post_id] %>
    <%= form.hidden_field :parent_comment_id, value: params[:id] %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

W8/W8D1/reddit_clone/reddit_clone/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

W8/W8D1/reddit_clone/reddit_clone/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Author</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.author %></td>
        <td><%= comment.post %></td>
        <td><%= link_to "Show", post_comment_url(comment.post, comment) %></td>
        <td><%= link_to "Edit", edit_comment_path(comment) %></td>
        <td><%= link_to "Destroy", comment, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

W8/W8D1/reddit_clone/reddit_clone/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render "form", comment: @comment %>

<%= link_to "Show", @comment %> |
<%= link_to "Back", comments_path %>

W8/W8D1/reddit_clone/reddit_clone/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author.username %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<% if @comment.comment %>
  <p>
    <strong>Parent:</strong>
    <%= link_to @comment.comment.content, post_comment_url(@comment.post, @comment.comment) %>
  </p>
  
<% end %>


<%= link_to "Edit", edit_comment_path(@comment) %> |
<%= link_to "Back", comments_path %>


<br>

<p>
  <strong>Comment Section</strong>

      <% @comment.child_comments.each do |comment| %>

          <%= render "comment", comment: comment %>

      <% end %>

  <br>
</p>


<strong>New Comment</strong>

<%= render "form", comment: Comment.new %>
<br>